### PR TITLE
added universal property of tensor product

### PR DESCRIPTION
**Pull request by Alizter**
I'm not sure if we can make these proofs any shorter.

### CODE REVIEW

**Comment by jdchristensen** [comment]
Since this is in an Algebra folder, not a Group folder, the file name Tensor is a bit generic.  (One can tensor abelian groups, modules over a commutative ring, vector spaces, algebras, etc.)  Would AbTensor be ok?  Or should we use AbelianGroupTensor?  But in fact, most of the file is about AbHom, so maybe the name should reflect that?  Or maybe it should just be in AbelianGroup.v?

Inside the file, probably IsTensor should be IsAbTensor?

**Comment by Alizter** [comment]
Well, one of the things I want to do in the main library is to organise Algebra better. My intention with this file was that "it would eventually land in a folder called AbGroup or something".

**Comment by Alizter** [comment]
Actually I think it would be better in AbelianGroup.v for now. I'll do this in a bit.

**Comment by jdchristensen** [comment]
Let's get those other changes to AbelianGroup.v into master.  Then we can rebase this on top of those changes, and I'll take a closer look.  BTW, after tomorrow I'm going to be away for a few weeks and won't be able to work much on things.

**Comment by Alizter** [comment]
@jdchristensen OK, thanks for letting me know!

**Comment by jdchristensen** [comment]
I've just merged master into this branch.  Can you rebase?

**Comment by Alizter** [comment]
@jdchristensen done.

**Comment by jdchristensen** [comment]
Thanks!

**Pull request merged**
