### PR TITLE
Some lemmas about natequivs and progress on 2.44

### PR DESCRIPTION
**Pull request by Alizter**
I've written some basic lemmas for working with NatEquivs. I've tried to push through with 2.44 as well. The equivalence is almost finished we just need lemma 2.24 and its naturality in the last variable. On top of this we will need to show that the 2.44 equivalence is natural in X and Y. This doesn't look easy but I haven't been able to really attempt it yet.

### CODE REVIEW

**Comment by jdchristensen** [comment]
Wow, this looks great!  Lemma 2.24 and its naturality are already done in PreGroup.v, as things with `loops_in` in their name.

It may be a few days before I can look this over carefully, so feel free to update it with the loops_in part in the meantime.

**Comment by Alizter** [comment]
I have managed to finish the equivalence in 2.44. However the naturality in X and Y looks really difficult.

I ran into a subtle issue with the natural equivalences, since we attach the "being functorial" instance to a regular function, you can get a goal like `NatEquiv (F o G o H) (F o G o H)` and be perplexed why it isn't reflexivity like I was. After thinking about it a bit more, I noticed that this is just associativity of functor composition! You can't see this with the functions, but the instances would be constructed in different ways. I've added a lemma [natequiv_functor_assoc_f_ff] to `NatTrans.v` for the associativity.

I think this is more empirical evidence that you cannot rely solely on an unbundled or bundled approach. You have to mix the approaches. If we used the record functors instead of just instances on functions, these structural differences would be more visible. At the cost of making it more difficult to work with.

Anyway, I will become a bit busier before next semester starts, so I might not be able to work on this for a bit. Feel free to merge this.

**Comment by jdchristensen** [comment]
Thanks for the impressive work!  Can you clarify the status of the three "Admitted" lines?  I'm guessing we can weaken the last claim from a natural equivalence to an equivalence to get rid of the last Admitted.  But what about the two earlier "Admitted" lines?  Are they needed to get the equivalence of 2.44?

**Comment by Alizter** [comment]
I've split apart 2.44 into the equivalence without the naturality to make it easier to do the following. I learnt this cool feature last week:
```coq
Print Opaque Dependencies pequiv_psusp_smash.
Print Assumptions pequiv_psusp_smash'.
```
The first one will list all the Opaque definitions/lemmas that `pequiv_psusp_smash` uses whereas the second one will list all the assumptions (axioms/admitteds).

Here are the axioms we are using:
```coq
Axioms:
sect2 : forall (H : Funext) (X Y Z : pType), Sect (pmap_uncurry X Y Z) (nested_pprecompose Z (psm X Y))
sect1 : forall (H : Funext) (X Y Z : pType), Sect (nested_pprecompose Z (psm X Y)) (pmap_uncurry X Y Z)
pmap_uncurry_nat_Z : forall (H : Funext) (X Y Z Z' : pType) (f : Z ->* Z'),
                     pmap_uncurry X Y Z' o* ppostcompose X (ppostcompose Y f) ==*
                     ppostcompose (Smash X Y) f o* pmap_uncurry X Y Z
istrunc_truncation : forall (n : trunc_index) (A : Type), IsTrunc n (Trunc n A)
isequiv_apD10 : Funext -> forall (A : Type) (P : A -> Type) (f g : forall x : A, P x), IsEquiv apD10
hard_coherence : forall (H : Funext) (X A B : pType) (f : A ->* B),
                 magma_loops_in_nat_r f (point (loops (ppforall _ : X, A))) =
                 dpoint_eq (magma_loops_in o* loops_functor (ppostcompose X f)) @
                 (dpoint_eq (ppostcompose X (loops_functor f) o* magma_loops_in))^
Coeq.Coeq.cglue : forall (B A : Type) (f g : B -> A) (b : B), Coeq.Coeq.coeq (f b) = Coeq.Coeq.coeq (g b)
Funext : Type0
Coeq.Coeq.Coeq_ind_beta_cglue : forall (B A : Type) (f g : B -> A) (P : Coeq.Coeq.Coeq f g -> Type)
                                (coeq' : forall a : A, P (Coeq.Coeq.coeq a))
                                (cglue' : forall b : B, transport P (Coeq.Coeq.cglue b) (coeq' (f b)) = coeq' (g b))
                                (b : B), apD (Coeq.Coeq.Coeq_ind P coeq' cglue') (Coeq.Coeq.cglue b) = cglue' b
```

The following can be ignored:
 * `istrunc_truncation` is the truncation decleration for the HIT
 * `isequiv_apD10` is funext
 * `Coeq.Coeq.cglue` is the path for coequalizers
 * `Funext` is just the universe independent parameter for Funext
 * `Coeq.Coeq.Coeq_ind_beta_cglue` is the computation rule for coequalizers.

This leaves us with four assumptions:
* `sect2 : forall (H : Funext) (X Y Z : pType), Sect (pmap_uncurry X Y Z) (nested_pprecompose Z (psm X Y))`
* `sect1 : forall (H : Funext) (X Y Z : pType), Sect (nested_pprecompose Z (psm X Y)) (pmap_uncurry X Y Z)`
* `pmap_uncurry_nat_Z` is the fact that pmap_uncurry ins natural in Z. This checks that the natuality homotopy (in Z) for pmap_uncurry is a pointed homotopy. This seems to be difficult to prove.
* `hard_coherence` is well a hard coherence. It is the fact that the natuality homotopy from lemma 2.24 is pointed. There is probably a clever way to prove this.

**Comment by jdchristensen** [comment]
Thanks, that's very helpful.  I believe that the first three have all been formalized by Floris in his Lean library and are part of the background that we are willing to take as axioms.  But the `hard_coherence` seems to be a gap, so it's still too early to say that the equivalence part of 2.44 has been proved.  I'll merge this and then see if I can handle it.

**Comment by jdchristensen** [comment]
I proved the `hard_coherence` (embedded in `magma_loops_in_nat_r`) in 20095cc7f36d5863bc74a71da5622414695a539c

**Comment by Alizter** [comment]
@jdchristensen That's great! Do you think it will be possible to prove 2.44 is natural in X and Y?

**Comment by jdchristensen** [comment]
Not sure.  Also not sure if we'll need this, except to know that the Hurewicz isomorphism is natural, which is lower priority than actually getting the isomorphism.  Thanks for doing 99% of the work on Lemma 2.44!

**Pull request merged**
