### PR TITLE
partially finished Lemma 2.42

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by jdchristensen** [comment]
Nice!  I just updated `pequiv_pmap_uncurry` with a cleaner argument.  Do you just need to know the underlying function of the equivalence?  If so (and even if not), we should split `pequiv_pmap_uncurry` into a definition of the map plus a separate axiom that says that the map is an equivalence.

**Comment by jdchristensen** [comment]
I won't edit the file right now, so you can change pequiv_pmap_uncurry to make things work.

**Comment by jdchristensen** [comment]
@Alizter  I think I'll commit this as is, unless you are in the middle of updating it.  Sound good?

**Comment by Alizter** [comment]
@jdchristensen sounds good.

**Comment by jdchristensen** [comment]
If you aren't in the middle of changes, I'll see if I can make it go through.

**Comment by jdchristensen** [comment]
@Alizter I finished the proof and pushed it.  I won't edit for a while.  Feel free to improve what I did, or start something new.

**Pull request merged**
